### ISSUE TITLE
Add Mi Smart Standing Fan 1C (dmaker.fan.1c) support

### ISSUE THREAD

**Issue by chiefmaster81** [syssi/xiaomi_fan#85] opened 2020-08-13 08:23 UTC
Hi,

I bought this and found your addon to home assistant. But it tells me:

2020-08-13 09:15:44 ERROR (MainThread) [custom_components.xiaomi_miio_fan.fan] Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_fan/issues and provide the following data: **dmaker.fan.1c**

It would be great if it is possible to integrate Support for it.
Also would be nice to be able to use DNS-names instead of IP-addresses for value "host" in config.

I hope you can do some magic on you fabulous add-on.

cheers,
Christian

**Comment by RichrdJ** [comment] 2020-08-13 17:17
+1, can't get it to work with the current config.

**Comment by bfbones** [comment] 2020-08-17 07:47
duplicate of #62

**Comment by janfajessen** [comment] 2020-09-08 23:23
I would also like to have the integration of the "Xiaomi Pedestal Fan 1C" model but in my case it tells me that it is the dmaker.fan.p8 model. And I managed to get the token out of him.

As a comparison to the options available in the supported fans, the dmaker.fan.p8 has 3 power levels and also a night mode that varies the breeze more or less power randomly.
Also, you can turn the oscillation on or off but not choose the angle.

I have seen that there is a dmaker.fan.p5 model, I don't know exactly what functions it has.
I don't know if changing the configuration manually to add my model would be enough to make it work, at the moment I don't dare to do it because I have almost no programming knowledge.

Thanks in advance

**Comment by janfajessen** [comment] 2020-09-10 07:50
I find this miot-spec, maybe this will be helpful for the programer:

{
type: "urn:miot-spec-v2:device:fan:0000A005:dmaker-1c:1",
description: "Fan",
services: [
{
iid: 1,
type: "urn:miot-spec-v2:service:device-information:00007801:dmaker-1c:1",
description: "Device Information",
properties: [
{
iid: 1,
type: "urn:miot-spec-v2:property:manufacturer:00000001:dmaker-1c:1",
description: "Device Manufacturer",
format: "string",
access: [
"read"
]
},
{
iid: 2,
type: "urn:miot-spec-v2:property:model:00000002:dmaker-1c:1",
description: "Device Model",
format: "string",
access: [
"read"
]
},
{
iid: 3,
type: "urn:miot-spec-v2:property:serial-number:00000003:dmaker-1c:1",
description: "Device Serial Number",
format: "string",
access: [
"read"
]
},
{
iid: 4,
type: "urn:miot-spec-v2:property:firmware-revision:00000005:dmaker-1c:1",
description: "Current Firmware Version",
format: "string",
access: [
"read"
]
}
]
},
{
iid: 2,
type: "urn:miot-spec-v2:service:fan:00007808:dmaker-1c:1",
description: "Fan",
properties: [
{
iid: 1,
type: "urn:miot-spec-v2:property:on:00000006:dmaker-1c:1",
description: "Switch Status",
format: "bool",
access: [
"read",
"write",
"notify"
]
},
{
iid: 2,
type: "urn:miot-spec-v2:property:fan-level:00000016:dmaker-1c:1",
description: "Fan Level",
format: "uint8",
access: [
"read",
"write",
"notify"
],
unit: "none",
value-list: [
{
value: 1,
description: "1"
},
{
value: 2,
description: "2"
},
{
value: 3,
description: "3"
}
]
},
{
iid: 3,
type: "urn:miot-spec-v2:property:horizontal-swing:00000017:dmaker-1c:1",
description: "Horizontal Swing",
format: "bool",
access: [
"read",
"write",
"notify"
]
},
{
iid: 7,
type: "urn:miot-spec-v2:property:mode:00000008:dmaker-1c:1",
description: "Mode",
format: "uint8",
access: [
"read",
"write",
"notify"
],
unit: "none",
value-list: [
{
value: 0,
description: "Straight Wind"
},
{
value: 1,
description: "Sleep"
}
]
},
{
iid: 10,
type: "urn:miot-spec-v2:property:off-delay-time:00000054:dmaker-1c:1",
description: "Power Off Delay Time",
format: "uint16",
access: [
"read",
"write",
"notify"
],
unit: "minutes",
value-range: [
0,
480,
1
]
},
{
iid: 11,
type: "urn:miot-spec-v2:property:alarm:00000012:dmaker-1c:1",
description: "Alarm",
format: "bool",
access: [
"read",
"write",
"notify"
]
},
{
iid: 12,
type: "urn:miot-spec-v2:property:brightness:0000000D:dmaker-1c:1",
description: "Brightness",
format: "bool",
access: [
"read",
"write",
"notify"
],
unit: "none"
}
],
actions: [
{
iid: 1,
type: "urn:miot-spec-v2:action:toggle:00002811:dmaker-1c:1",
description: "Toggle",
in: [ ],
out: [ ]
}
]
},
{
iid: 3,
type: "urn:miot-spec-v2:service:physical-controls-locked:00007807:dmaker-1c:1",
description: "Physical Control Locked",
properties: [
{
iid: 1,
type: "urn:miot-spec-v2:property:physical-controls-locked:0000001D:dmaker-1c:1",
description: "Physical Control Locked",
format: "bool",
access: [
"read",
"write",
"notify"
]
}
]
}
]
}

**Comment by Gertjuh** [comment] 2020-10-09 17:40
I also have this error:

Logger: custom_components.xiaomi_miio_fan.fan
Source: custom_components/xiaomi_miio_fan/fan.py:274
Integration: xiaomi_miio_fan (documentation)
First occurred: 9:15:27 (1 occurrences)
Last logged: 9:15:27

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_fan/issues and provide the following data: dmaker.fan.1c

Is there a solution?

**Comment by jeansmicke** [comment] 2020-11-19 19:19
Same problem for me too. Had it working in 1.0 but it broke when I upgraded to 2.0. I've tried reinstalling 1.0 but still get the same error.

**Comment by marcandre83** [comment] 2021-01-03 10:24
Same problem for me, i think dmaker isn't supported yet.

**Comment by arduinopjotr** [comment] 2021-02-16 16:42
great if ypu can support  the 1c version.

**Comment by schmidiij** [comment] 2021-04-07 14:37
is there any updates?

**Comment by syssi** [comment] 2021-04-10 15:26
I prepared a PR at `python-miio` to support the device: https://github.com/rytilahti/python-miio/pull/1012

**Comment by matteos1** [comment] 2021-04-20 08:52
please add support to dmaker.fa.1c. thank you

**Comment by wild-run** [comment] 2021-05-01 11:32
please yes :)

**Comment by sokopower** [comment] 2021-05-02 11:04
I have 2 units of Mi Smart Stading Fan model JLLDS01XY
Could you support of dmaker.fan.1c, please?

Thank you very much! 🙏🏼
Regards

**Comment by kenge1967** [comment] 2021-05-04 16:46
I want it too

**Closed** 2021-05-06 20:39 UTC
Labels: miot-protocol, new-device
