### ISSUE TITLE
Add zhimi.fan.fa1 support please

### ISSUE THREAD

**Issue by wfchan** [syssi/xiaomi_fan#93] opened 2020-12-02 05:01 UTC
Add zhimi.fan.fa1 support please

**Comment by syssi** [comment] 2021-01-18 08:38
Duplicate of #79.

**Closed by syssi** 2021-01-18 08:38 UTC
Labels: miot-protocol, new-device

**Comment by Cyberlenin** [comment] 2022-09-21 14:22
But it's still not supported.
`Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_fan/issues and provide the following data: zhimi.fan.fa1`
