### ISSUE TITLE
add support for  dmaker.fan.p45

### ISSUE THREAD

**Issue by ZinchenkoAndrew** [syssi/xiaomi_fan#266] opened 2024-08-05 16:47 UTC
Error message: Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_fan/issues and provide the following data: dmaker.fan.p45

**Comment by syssi** [comment] 2024-08-14 06:03
This is a duplicate of #214.

**Closed by syssi** 2024-08-14 06:03 UTC
