### ISSUE TITLE
fan_set_delay_off is in seconds for Smartmi Standing Fan 3 (zhimi.fan.za5)

### ISSUE THREAD

**Issue by popy2k14** [syssi/xiaomi_fan#194] opened 2022-06-29 20:09 UTC
I have an Smartmi Standing Fan 3 (zhimi.fan.za5) integrated with this custom component.

When i run

`
service: xiaomi_miio_fan.fan_set_delay_off
data_template:
  entity_id: fan.ventilator
  delay_off_countdown: 480
`

This results in 8 minutes (8 * 60) in turn off delay (also shown in Mi Home App).
Sadly the value is capped at max. 480, so i cant set an turn off delay longer than 8 minutes.

Can this please be fixed?
Fast approach: Dont use a list of possible value's, instead uncap the int.

**Comment by syssi** [comment] 2022-06-29 20:17
Do you like to create a pull request? This line must be changed:

https://github.com/syssi/xiaomi_fan/blob/0aead13f4eb655a05b93f617f170d907b2a67cf3/custom_components/xiaomi_miio_fan/fan.py#L339

I suggest a `cv.positive_int` validation instead.

**Comment by syssi** [comment] 2022-06-30 04:56
I've relaxed the validation and I've changed the value of the setter from seconds to minutes. You have to pass minutes in future! The value `480` means 8 hours now. Please give it a try!

**Comment by popy2k14** [comment] 2022-06-30 06:01
thx for the quick fix.
Will give it a try in the evening and report back.

**Comment by syssi** [comment] 2022-06-30 06:11
If it is working as intended I will prepare a release afterwards.

**Comment by popy2k14** [comment] 2022-06-30 07:56
Tested and it works as it should.
I think it's ready for a commit.

PS.: does this not have any impact on other fan types?

thanks

**Comment by popy2k14** [comment] 2022-06-30 08:27
ok, got you, than we should be good to go.

**Comment by syssi** [comment] 2022-07-17 08:56
Fixed by https://github.com/syssi/xiaomi_fan/commit/f22db51a5a49c6b5dd97f66c559fe3d187fb3a66.

**Closed by syssi** 2022-07-17 08:56 UTC
