### ISSUE TITLE
XiaoMi Smart Standing Fan 1C (recent model from 5/2020) not working in HASS

### ISSUE THREAD

**Issue by rvandenwijngaard** [syssi/xiaomi_fan#81] opened 2020-07-29 23:46 UTC
Can you add new type Xiaomi Mi Smart Standing Fan 1C ... (dmaker.fan.1c) to the custom component script? thx Rene.

**Comment by insajd** [comment] 2020-08-03 15:27
This is duplicate of https://github.com/syssi/xiaomi_fan/issues/62 and should be closed.

**Closed** 2020-08-06 10:12 UTC
