### ISSUE TITLE
Support for dmaker.fan.1c ?

### ISSUE THREAD

**Issue by antraxfpv** [syssi/xiaomi_fan#78] opened 2020-07-22 23:02 UTC
Hellow 

Its posible this fan works?

**Comment by insajd** [comment] 2020-08-03 15:27
This is duplicate of https://github.com/syssi/xiaomi_fan/issues/62 and should be closed.

**Comment by antraxfpv** [comment] 2020-08-06 01:40
Thanks

**Closed** 2020-08-06 01:40 UTC
