### ISSUE TITLE
Add dmaker.fan.1c support

### ISSUE THREAD

**Issue by Mohannadsharief** [syssi/xiaomi_fan#101] opened 2021-03-04 09:38 UTC
Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_fan/issues and provide the following data: dmaker.fan.1c

**Comment by syssi** [comment] 2021-04-10 14:54
This device model wasn't supported ever. Did you use another `model` at your configuration at the past?

**Comment by syssi** [comment] 2021-04-10 15:24
A fork which supports the model at the moment: https://github.com/damianpasek/xiaomi_fan

A first step to support the device offically: https://github.com/rytilahti/python-miio/pull/1012

**Comment by syssi** [comment] 2021-04-10 15:33
Duplicate of #85.

**Closed by syssi** 2021-04-10 15:33 UTC
Labels: new-device
