### ISSUE TITLE
Add dmaker.fan.p5c support

### ISSUE THREAD

**Issue by HASSAAS** [syssi/xiaomi_fan#269] opened 2024-08-12 00:52 UTC
Hello! Can I add support for Mijia Smart DC Standing Fan 1X? thank you
https://home.miot-spec.com/s/dmaker.fan.p5c#google_vignette

**Comment by syssi** [comment] 2024-08-12 06:39
You are welcome to contribute the device support!

**Comment by syssi** [comment] 2024-08-14 05:58
This is a duplicate of #254.

**Closed by syssi** 2024-08-14 05:58 UTC
Labels: new-device, miot-protocol
