### ISSUE TITLE
Please add support xiaomi smart tower fan 2 to Home assistant (dmaker.fan.p45)

### ISSUE THREAD

**Issue by akrush24** [syssi/xiaomi_fan#249] opened 2024-05-02 21:12 UTC
I would like to request support for the dmaker.fan.p45 model.

```2024-05-02 23:55:35.166 ERROR (MainThread) [custom_components.xiaomi_miio_fan.fan] Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_fan/issues and provide the following data: dmaker.fan.p45```

**Comment by Sungurik** [comment] 2024-05-15 10:30
+1

**Comment by unegade** [comment] 2024-06-17 21:07
+1

**Comment by sanyafifa** [comment] 2024-06-29 10:26
+1

**Comment by igzvaric** [comment] 2024-07-04 07:35
+1

**Comment by syssi** [comment] 2024-08-14 06:03
This is a duplicate of #214.

**Closed by syssi** 2024-08-14 06:03 UTC

**Comment by vismuthxx** [comment] 2025-03-03 08:13
+1

**Comment by vismuthxx** [comment] 2025-03-03 08:15
The fan has not been added like this since 2025.

**Comment by gokhanhotan** [comment] 2025-07-22 12:00
+1
