### ISSUE TITLE
windows homeassistant (not raspberry ) error unrecognizable

### ISSUE THREAD

**Issue by zhsyzx** [syssi/xiaomi_fan#10] opened 2018-06-06 09:28 UTC
windows homeassistant (not raspberry )Install this component error unrecognizable

xiaomi_miio_fan: Error on device update!
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-packages\homeassistant\helpers\entity_platform.py", line 244, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-packages\homeassistant\helpers\entity.py", line 325, in async_device_update
    yield from self.async_update()
  File "C:\Users\Administrator\AppData\Roaming\.homeassistant\custom_components\fan\xiaomi_miio_fan.py", line 390, in async_update
    self._natural_mode = (state.natural_speed != 0)
AttributeError: 'FanStatus' object has no attribute 'natural_speed'

Error doing job: Exception in callback _ProactorReadPipeTransport._loop_reading(<_OverlappedF...op_reading()]>)
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\asyncio\proactor_events.py", line 189, in _loop_reading
    data = fut.result()  # deliver data later in "finally" clause
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\asyncio\futures.py", line 288, in result
    raise InvalidStateError('Result is not ready.')
asyncio.futures.InvalidStateError: Result is not ready.

**Comment by zhsyzx** [comment] 2018-06-06 14:58
Upgrade 0.4.0 still does not recognize
Log Details (ERROR)
Error while setting up platform xiaomi_miio_fan
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-packages\homeassistant\helpers\entity_platform.py", line 129, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\asyncio\tasks.py", line 406, in wait_for
    return fut.result()
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\asyncio\tasks.py", line 240, in _step
    result = coro.send(None)
  File "C:\Users\Administrator\AppData\Roaming\.homeassistant\custom_components\fan\xiaomi_miio_fan.py", line 199, in async_setup_platform
    fan = Fan(host, token, model=model)
TypeError: __init__() got an unexpected keyword argument 'model'

**Comment by syssi** [comment] 2018-06-06 17:33
HA downgrades the dependency on startup. Please start bin/hass with `--skip-pip`.

**Comment by zhsyzx** [comment] 2018-06-07 09:44
hass --skip-pip  can't be identified 
Error doing job: Exception in callback _ProactorReadPipeTransport._loop_reading(<_OverlappedF...op_reading()]>)
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\asyncio\proactor_events.py", line 189, in _loop_reading
    data = fut.result()  # deliver data later in "finally" clause
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\asyncio\futures.py", line 288, in result
    raise InvalidStateError('Result is not ready.')
asyncio.futures.InvalidStateError: Result is not ready.

Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-packages\homeassistant\helpers\entity_platform.py", line 129, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\asyncio\tasks.py", line 406, in wait_for
    return fut.result()
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\asyncio\tasks.py", line 240, in _step
    result = coro.send(None)
  File "C:\Users\Administrator\AppData\Roaming\.homeassistant\custom_components\fan\xiaomi_miio_fan.py", line 199, in async_setup_platform
    fan = Fan(host, token, model=model)
TypeError: __init__() got an unexpected keyword argument 'model'

**Comment by syssi** [comment] 2018-06-08 21:09
You could wait for HA 0.71. This will fix the issue because all components will use the same python-miio version again. All of your posted errors are caused by an old python-miio version.

**Comment by MimbaMonkeyHouse** [comment] 2018-06-10 06:03
0.71 was released. @zhsyzx can you confirm this now works?

**Comment by syssi** [comment] 2018-06-13 06:10
I was wrong: python-miio 0.4.0 will be part of 0.72.

**Comment by syssi** [comment] 2018-08-21 12:06
Should be fixed. Please reopen the issue if not.

**Closed by syssi** 2018-08-21 12:06 UTC
