### ISSUE TITLE
BPTS02DM support?

### ISSUE THREAD

**Issue by joshuaboniface** [syssi/xiaomi_fan#244] opened 2024-01-06 22:09 UTC
This component explicitly lists the BPTS01DM as compatible, but is the BPTS02DM also compatible?

**Comment by hpirila** [comment] 2024-01-11 12:28
No, it is currently not compatible. This issue is already reported here #214.

**Comment by hpirila** [comment] 2024-01-14 04:26
See #214 for a workaround.

**Comment by syssi** [comment] 2024-08-14 06:05
This is a duplicate of #214.

**Closed by syssi** 2024-08-14 06:05 UTC
